### ISSUE TITLE
Huge logs

### ISSUE THREAD

**Issue by kylegordon** [bazwilliams/upnp-sub-mqtt#5]
Monring!

Unfortunately there's been some sort of error, and there's now a 17GB log file, which filled my docker partition to the limit...

-rw-r----- 1 root root 17G Sep 25 07:27 /var/lib/docker/containers/3c60f8343c9c2d21ad33db5382f1cf24c27882e55f099b6797b82b958551de65/3c60f8343c9c2d21ad33db5382f1cf24c27882e55f099b6797b82b958551de65-json.log

This file is what's specified as the docker LogPath. However, upnp-sub-mqtt is at the top of the CPU list and docker is refusing to connect to it, show any logs, stop it, etc

An example of the repaeating log output is...

`{"log":"  syscall: 'connect',\n","stream":"stderr","time":"2016-09-25T03:33:41.070604674Z"}
{"log":"  address: '172.17.0.1',\n","stream":"stderr","time":"2016-09-25T03:33:41.070614394Z"}
{"log":"  port: 49152 }\n","stream":"stderr","time":"2016-09-25T03:33:41.070624915Z"}
{"log":"Linux/4.4.0-38-generic, UPnP/1.0, Portable SDK for UPnP devices/1.6.19+git20160116@http://172.17.0.1:49152/description.xml [uuid:a632e261-f30b-cb3a-cce8-0242facc85ee::urn:av-openhome-org:service:Radio:1]: Error: connect ECONNREFUSED 172.17.0.1:49152\n","stream":"stderr","time":"2016-09-25T03:33:41.070635622Z"}
{"log":"{ [Error: connect ECONNREFUSED 172.17.0.1:49152]\n","stream":"stderr","time":"2016-09-25T03:33:41.070647157Z"}
{"log":"  code: 'ECONNREFUSED',\n","stream":"stderr","time":"2016-09-25T03:33:41.070657186Z"}
{"log":"  errno: 'ECONNREFUSED',\n","stream":"stderr","time":"2016-09-25T03:33:41.070666822Z"}
{"log":"  syscall: 'connect',\n","stream":"stderr","time":"2016-09-25T03:33:41.070682878Z"}
{"log":"  address: '172.17.0.1',\n","stream":"stderr","time":"2016-09-25T03:33:41.070698409Z"}
{"log":"  port: 49152 }\n","stream":"stderr","time":"2016-09-25T03:33:41.070708855Z"}
{"log":"Linux/4.4.0-38-generic, UPnP/1.0, Portable SDK for UPnP devices/1.6.19+git20160116@http://172.17.0.1:49152/description.xml [uuid:a632e261-f30b-cb3a-cce8-0242facc85ee::urn:av-openhome-org:service:Receiver:1]: Error: connect ECONNREFUSED 172.17.0.1:49152\n","stream":"stderr","time":"2016-09-25T03:33:41.07072405Z"}
{"log":"{ [Error: connect ECONNREFUSED 172.17.0.1:49152]\n","stream":"stderr","time":"2016-09-25T03:33:41.070740835Z"}
{"log":"  code: 'ECONNREFUSED',\n","stream":"stderr","time":"2016-09-25T03:33:41.07075111Z"}
{"log":"  errno: 'ECONNREFUSED',\n","stream":"stderr","time":"2016-09-25T03:33:41.070760713Z"}
{"log":"  syscall: 'connect',\n","stream":"stderr","time":"2016-09-25T03:33:41.070770115Z"}
{"log":"  address: '172.17.0.1',\n","stream":"stderr","time":"2016-09-25T03:33:41.070785109Z"}
{"log":"  port: 49152 }\n","stream":"stderr","time":"2016-09-25T03:33:41.07
`

172.17.0.1 is the address associated with the docker0 bridge.

Happy Sunday! :-)

**Comment by bazwilliams** [comment]
Are you running an open home player under docker? Looks like it has discovered something on that network and tried to connect. 

I've a similar issue with something being discovered but can't be described. I've mooted the idea a blacklisting the UDN after some number of failed attempts. 

What docker tag were you running? There is now a 5 minute wait before a failed description download is reattempted.

**Comment by kylegordon** [comment]
Nope, no OHPlayer. The only things I have in docker just now are rancher agents, minimserver, and upnp-sub-mqtt.

Currently on tag 2. Shall I try latest?

**Comment by bazwilliams** [comment]
Definitely move to latest, that version will immediately retry on failure.
Are you running minim in `--net=host` mode? I'll check my docker logs as I
also have minim running.

**Comment by kylegordon** [comment]
Righto, on latest and it's doing this, oddly, 104 times a minute. It's all in one big burst though, and then silence for 59 seconds.

`2016-09-25T10:19:34.684Z ERROR Linux/4.4.0-38-generic, UPnP/1.0, Portable SDK for UPnP devices/1.6.19+git20160116@http://172.17.0.1:49152/description.xml [uuid:a632e261-f30b-cb3a-cce8-0242facc85ee::urn:av-openhome-org:service:Receiver:1]: Error: connect ECONNREFUSED 172.17.0.1:49152
2016-09-25T10:19:34.684Z ERROR 
        {"message":"connect ECONNREFUSED 172.17.0.1:49152","stack":"Error: connect ECONNREFUSED 172.17.0.1:49152\n    at Object.exports._errnoException (util.js:907:11)\n    at exports._exceptionWithHostPort (util.js:930:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"172.17.0.1","port":49152}
2016-09-25T10:19:34.685Z WARN Rolling back subscriptions
`

minimserver is running in host network mode. 

I don't know what's supposed to be running on port 49152... there's nothing listening on it at this point unfortunately.

**Comment by bazwilliams** [comment]
Something is responding to an m-search and advertising itself as an
openhome receiver with that address.
